### PR TITLE
FInal Merge

### PR DESCRIPTION
**Pull request by charlesgobina**
For this Milestone, I
* Created a rails API to serve as the backend for a react front end application [hello-react-front-end](https://github.com/charlesgobina/hello-react-front-end)
* Here's the PR for the frontend [frontend-pull-request](https://github.com/charlesgobina/hello-react-front-end/pull/4)
* Front end uses [localhost:3001](http://localhost:3001/)
* Back end uses [localhost:3000](http://localhost:3000/)

### CODE REVIEW

**Review by micheaol — CHANGES_REQUESTED** [review]
Hi @charlesgobina , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a frontend app without a PR with changes

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by micheaol — CHANGES_REQUESTED** [review]
Hi @charlesgobina , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a frontend app without a PR with changes

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by charlesgobina** [comment]
Hello @micheaol,

Thank you for the feedback. Please, this project is the backend built with rails. Please kindly check and look through it again.

Best,

**Comment by micheaol** [comment]
@charlesgobina,

You developed two apps, frontend, and backend. According to the project requirements, both of them should have a PR of the changes made. Now you have a PR for the backend but you do not have a PR for the frontend.  Kindly create a PR for the front end and resubmit for re-review. 

I hope the requirement is clearer now.

**Comment by charlesgobina** [comment]
Thank you @micheaol

**Review by elyor-doniyorov — APPROVED** [review]
Hi @charlesgobina, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
